apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/kubernetesStorage/postgresDb/  # Path on the host where the database data will be stored
    type: Directory
