apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphkb-database-pv-claim
  namespace: graphkb
spec:
  storageClassName: microk8s-hostpath
  #reclaimPolicy: retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
