apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipr-database
  namespace: ipr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/kubernetesStorage/postgresDb/  # Path on the host where the dump file is stored
    type: Directory
