apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: graphkb-db-claim1
  name: db-claim1
  namespace: graphkb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
