apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphkb-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kubernetesStorage/"
    type: DirectoryOrCreate