apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.dev.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ipr-api
  name: api
  namespace: ipr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ipr-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.dev.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ipr-api
    spec:
      containers:
        - args:
            - npm 
            - start
          image: bcgsc/pori-ipr-api:uofc
          imagePullPolicy: IfNotPresent
          env:
            - name: IPR_DATABASE_HOSTNAME
              value: "ipr_db"
            - name: IPR_DATABASE_NAME
              value: "ipr_demo"
            - name: IPR_DATABASE_PASSWORD
              value: "root"
            - name: IPR_DATABASE_USERNAME
              value: "ipr_ro"
            - name: IPR_GRAPHKB_PASSWORD
              value: "ipr_graphkb_link"
            - name: IPR_GRAPHKB_URI
              #value: "http://graphkb_api:8080/api"
              value: "http://api.graphkb.svc.cluster.loal:8080/api"
            - name: IPR_GRAPHKB_USERNAME
              value: "ipr_graphkb_link"
            - name: IPR_KEYCLOAK_KEYFILE
              value: "/keys/keycloak.key"
            - name: IPR_KEYCLOAK_URI
              #value: "http://keycloak:8888/auth/realms/PORI/protocol/openid-connect/token"
              value: "http://keycloak.security.svc.cluster.local:8888/auth/realms/PORI/protocol/openid-connect/token"
            - name: IPR_REDIS_HOST
              value: "redis"
            - name: IPR_REDIS_PORT
              value: "6379"
          #livenessProbe:
          #  exec:
          #    command:
          #      - curl
          #      - -f
          #      - http://ipr_api:8080/api/spec.json
          #  failureThreshold: 5
          #  periodSeconds: 30
          #  timeoutSeconds: 10
          name: ipr-api
          ports:
            - containerPort: 8080
              #protocol: TCP
          volumeMounts:
            - mountPath: /keys
              name: ipr-api-cm0
              readOnly: true
          #resources:
          #  limits:
          #    memory: 512Mi
          #    cpu: "1"
          #  requests:
          #    memory: 256Mi
          #    cpu: "0.2"
      restartPolicy: Always
      volumes:
        - configMap:
            name: ipr-api-cm0
          name: ipr-api-cm0
