apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphkb-database-pv
  labels:
    type: local
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/kubernetesStorage/"
    type: DirectoryOrCreate