# example-csi-snapshot.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ipr-postgres-snapshot
spec:
  volumeSnapshotClassName: ipr-postgres-snap
  source:
    persistentVolumeClaimName: ipr-database-claim