apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipr-database-claim
  namespace: ipr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-hostpath-sc
